import type { Metadata } from "next"
import {
  LegalShell,
  LegalSection,
  P,
  UL,
  Strong,
} from "@/components/legal/legal-shell"

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "The terms that govern your use of the Zerro app and website.",
  alternates: { canonical: "/terms" },
}

const LAST_UPDATED = "June 15, 2026"

export default function TermsPage() {
  return (
    <LegalShell title="Terms of Service" lastUpdated={LAST_UPDATED}>
      <LegalSection title="Agreement">
        <P>
          These Terms of Service (&ldquo;Terms&rdquo;) are a contract between
          you and <Strong>SmartScale Solutions LLC</Strong>{" "}
          (&ldquo;SmartScale&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;), the
          operator of the Zerro macOS application and the getzerro.app website
          (together, the &ldquo;Service&rdquo;). By creating an account,
          purchasing a plan, or using the Service, you agree to these Terms
          and to our{" "}
          <a
            href="/privacy"
            className="text-foreground underline underline-offset-4"
          >
            Privacy Policy
          </a>
          . If you do not agree, do not use the Service.
        </P>
      </LegalSection>

      <LegalSection title="The Service">
        <P>
          Zerro lets you record a region of your screen, dictate voice
          instructions, and receive AI-generated output such as a structured
          prompt for a coding agent. Output is generated by third-party AI
          models and may be inaccurate or incomplete — review it before
          relying on it. We may change, improve, or discontinue features over
          time.
        </P>
      </LegalSection>

      <LegalSection title="Accounts">
        <P>
          You must provide accurate information when creating an account and
          keep your credentials secure. You are responsible for activity under
          your account. You must be at least 13 years old (or the minimum age
          in your jurisdiction) to use the Service.
        </P>
      </LegalSection>

      <LegalSection title="Plans, billing, and credits">
        <UL>
          <li>
            <Strong>Managed plan.</Strong> A recurring subscription billed
            through Lemon Squeezy, our merchant of record. Generations consume
            credits that vary by model; unused credits do not roll over unless
            stated otherwise. Optional top-up packs may be available.
          </li>
          <li>
            <Strong>BYOK license.</Strong> A one-time license that lets you
            use your own API keys (OpenAI, Google, Anthropic). The license
            includes one year of app updates; after that, prior versions keep
            working but a new license is required for newer versions. You pay
            your AI providers directly for usage, and your provider
            relationships are governed by their terms.
          </li>
          <li>
            <Strong>Trial.</Strong> Free trial credits require email
            verification and are limited per person. We may adjust or revoke
            trial access to prevent abuse.
          </li>
        </UL>
        <P>
          Prices may change; changes to recurring prices take effect at your
          next billing period after notice. Refunds are handled in accordance
          with Lemon Squeezy&rsquo;s policies and applicable law — contact{" "}
          <a
            href="mailto:support@getzerro.app"
            className="text-foreground underline underline-offset-4"
          >
            support@getzerro.app
          </a>{" "}
          and we&rsquo;ll do our best to make it right.
        </P>
      </LegalSection>

      <LegalSection title="Acceptable use">
        <P>You agree not to:</P>
        <UL>
          <li>Use the Service to violate any law or the rights of others, including recording content you do not have the right to capture.</li>
          <li>Attempt to bypass credit accounting, rate limits, trial restrictions, or license enforcement.</li>
          <li>Reverse engineer, resell, or redistribute the Service except as permitted by law.</li>
          <li>Use the Service to develop a competing product by systematically extracting its outputs or behavior.</li>
          <li>Interfere with or disrupt the integrity or performance of the Service.</li>
          {/* DRAFT — placeholder language pending attorney review */}
          <li>Use the Service to capture, submit, or process data subject to special legal protection — including protected health information under HIPAA, payment card data subject to PCI-DSS, or similar regulated categories. The Service is not designed or offered for such use, and you bear sole responsibility and liability for any such data you choose to submit.</li>
        </UL>
      </LegalSection>

      <LegalSection title="Your content">
        <P>
          You retain all rights to your recordings and to the output generated
          from them. You grant us a limited license to process your recordings
          solely to provide the Service, as described in our Privacy Policy.
          We do not store your recordings and we do not use them to train AI
          models. You are responsible for ensuring you have the right to
          record the content on your screen and any audio you capture.
        </P>
      </LegalSection>

      {/* DRAFT — placeholder language pending attorney review */}
      <LegalSection title="Indemnification">
        <P>
          You agree to indemnify, defend, and hold harmless SmartScale
          Solutions LLC and its members from any third-party claims, damages,
          losses, and reasonable legal fees arising out of: (a) content you
          record or submit, including content you lacked the right to capture;
          (b) your violation of these Terms or applicable law; and (c) your
          submission of any data in violation of the regulated-data restriction
          in the Acceptable use section.
        </P>
      </LegalSection>

      <LegalSection title="Third-party services">
        <P>
          The Service depends on third parties, including AI model providers
          (OpenAI, Google, Anthropic), Supabase, Lemon Squeezy, Resend, and
          Vercel. We are not responsible for third-party services, and your
          use of your own API keys on the BYOK plan is subject to the relevant
          provider&rsquo;s terms.
        </P>
      </LegalSection>

      <LegalSection title="Intellectual property">
        <P>
          The Service, including the app, website, and branding, is owned by
          SmartScale and protected by intellectual property laws. We grant you
          a limited, non-exclusive, non-transferable license to use the app
          for its intended purpose. Feedback you provide may be used by us
          without obligation.
        </P>
      </LegalSection>

      <LegalSection title="Disclaimers">
        <P>
          THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS
          AVAILABLE&rdquo; WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED,
          INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
          NON-INFRINGEMENT. AI-GENERATED OUTPUT MAY CONTAIN ERRORS; YOU ARE
          RESPONSIBLE FOR REVIEWING IT BEFORE USE.
        </P>
        {/* DRAFT — placeholder language pending attorney review */}
        <P>
          Zerro&rsquo;s output, including plain-language explanations and
          answers, is provided for general informational purposes only, is
          generated by third-party AI models, and does not constitute
          professional advice of any kind (including legal, medical, financial,
          or tax advice). You should not rely on output as a substitute for a
          qualified professional.
        </P>
      </LegalSection>

      <LegalSection title="Limitation of liability">
        <P>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, SMARTSCALE WILL NOT BE
          LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR
          PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, DATA, OR GOODWILL. OUR
          TOTAL LIABILITY FOR ANY CLAIM ARISING OUT OF THE SERVICE WILL NOT
          EXCEED THE AMOUNT YOU PAID US IN THE TWELVE MONTHS BEFORE THE CLAIM
          AROSE. SOME JURISDICTIONS DO NOT ALLOW THESE LIMITATIONS, SO THEY
          MAY NOT APPLY TO YOU.
        </P>
      </LegalSection>

      <LegalSection title="Termination">
        <P>
          You may stop using the Service and delete your account at any time.
          We may suspend or terminate your access if you materially breach
          these Terms, including abuse of trials, credits, or rate limits.
          Sections that by their nature should survive termination (such as
          intellectual property, disclaimers, and limitation of liability)
          survive.
        </P>
      </LegalSection>

      <LegalSection title="Governing law">
        <P>
          These Terms are governed by the laws of the State of Wyoming,
          without regard to conflict of law principles. Disputes will be
          resolved in the state or federal courts located in Wyoming, and you
          consent to their jurisdiction.
        </P>
      </LegalSection>

      {/* DRAFT — placeholder language pending attorney review. This arbitration and class-action waiver clause in particular needs attorney review for enforceability in the governing-law jurisdiction (Wyoming); the opt-out mechanism and any consumer carve-outs must be confirmed. */}
      <LegalSection title="Dispute resolution">
        <P>
          Except where prohibited by law, any dispute arising out of or
          relating to these Terms or the Service will be resolved through
          binding individual arbitration rather than in court. You and
          SmartScale each waive the right to a jury trial and the right to
          participate in any class or representative action. You may opt out of
          this arbitration agreement by emailing{" "}
          <a
            href="mailto:support@getzerro.app"
            className="text-foreground underline underline-offset-4"
          >
            support@getzerro.app
          </a>{" "}
          within 30 days of first accepting these Terms.
        </P>
      </LegalSection>

      <LegalSection title="Changes to these Terms">
        <P>
          We may update these Terms from time to time. We will post the
          updated version on this page and revise the &ldquo;Last
          updated&rdquo; date; material changes will be notified more
          prominently. Continued use after changes take effect constitutes
          acceptance.
        </P>
      </LegalSection>

      <LegalSection title="Contact">
        <P>
          SmartScale Solutions LLC ·{" "}
          <a
            href="mailto:support@getzerro.app"
            className="text-foreground underline underline-offset-4"
          >
            support@getzerro.app
          </a>
        </P>
      </LegalSection>
    </LegalShell>
  )
}
