import type { Metadata } from "next"
import {
  LegalShell,
  LegalSection,
  P,
  UL,
  Strong,
} from "@/components/legal/legal-shell"
import {
  LICENSED_RELEASES,
  LICENSE_MAC_COUNT,
  LICENSE_PRICE,
  NEXT_MAJOR,
  SOURCE_LICENSE,
  TRIAL_DAYS,
} from "@/lib/product-facts"

// LEGAL REVIEW: the Agreement, Open source, Intellectual property, Acceptable
// use, Your recordings, Indemnification, Third-party services, and Termination
// sections draw the boundary between the GPL-3.0-or-later grant
// (which covers the source AND the covered code in official builds) and what
// the one-time purchase actually buys (SmartScale's signed/notarized
// distribution, official update service, and support). Owner/legal should
// confirm the final wording before publishing.

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "The terms for SmartScale's commercial services around Zerro: the website, checkout, license activation, official distribution, updates, support, and trademarks.",
  alternates: { canonical: "/terms" },
}

const LAST_UPDATED = "August 24, 2026"

export default function TermsPage() {
  return (
    <LegalShell title="Terms of Service" lastUpdated={LAST_UPDATED}>
      <LegalSection title="Agreement">
        <P>
          These Terms of Service (&ldquo;Terms&rdquo;) are a contract between
          you and <Strong>SmartScale Solutions LLC</Strong>{" "}
          (&ldquo;SmartScale&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;). They
          govern the commercial services SmartScale provides around the Zerro
          macOS application: the getzerro.app website, checkout, license
          activation, our official signed and notarized distribution, the
          official update service, support, and use of the Zerro trademarks
          (together, the &ldquo;Service&rdquo;). By purchasing a license,
          activating one, or using the website, checkout, update service, or
          support, you agree to these Terms and to our{" "}
          <a
            href="/privacy"
            className="text-foreground underline underline-offset-4"
          >
            Privacy Policy
          </a>
          . If you do not agree, do not use the Service.
        </P>
        <P>
          The Zerro application itself is free software licensed under the GNU
          General Public License, version 3 or later ({SOURCE_LICENSE}).
          Consistent with section 9 of that license, you are not required to
          accept these Terms in order to receive or run a copy of the
          application, including an official build. Your rights to copy,
          modify, and redistribute the application are governed solely by{" "}
          {SOURCE_LICENSE}, not by these Terms, and nothing in these Terms adds
          any restriction to a right that license grants.
        </P>
      </LegalSection>

      <LegalSection title="Zerro">
        <P>
          Zerro lets you record a region of your screen, dictate voice
          instructions, and receive AI-generated output such as a structured
          prompt for a coding agent. Zerro is bring-your-own-key: output is
          generated by the third-party AI provider you choose, using your own
          API key, and it may be inaccurate or incomplete; review it before
          relying on it. We may change, improve, or discontinue features of
          the official builds we distribute over time.
        </P>
      </LegalSection>

      <LegalSection title="No accounts">
        <P>
          Zerro does not require a Zerro account. The free trial, your provider
          API keys, your license key, and the local activation credentials are
          stored on your Mac; Lemon Squeezy, our merchant of record, processes
          the purchase and retains the purchase, activation, and device
          records needed to operate your license. Keep your license key and
          provider API keys secure; you are responsible for activity through
          them. You must be at least 13 years old (or the minimum age in your
          jurisdiction) to use the Service.
        </P>
      </LegalSection>

      <LegalSection title="Trial, license, and billing">
        <UL>
          <li>
            <Strong>Free trial.</Strong> The first time an official build runs
            on a Mac it begins a {TRIAL_DAYS}-day free trial, recorded on that
            Mac; reinstalling the app does not reset it. No card, email, or
            account is required, but you need your own supported provider API
            key to generate, and your AI providers may charge you for usage
            during the trial. We may adjust or revoke trial access to prevent
            abuse.
          </li>
          <li>
            <Strong>Zerro license.</Strong> After the trial, an official build
            asks for a Zerro license before it keeps generating. A license is
            sold for a one-time price of {LICENSE_PRICE} through Lemon
            Squeezy, our merchant of record. One license may be active on up
            to {LICENSE_MAC_COUNT} Macs at the same time; you can deactivate a
            Mac in the Lemon Squeezy customer portal to move the license. The
            license covers every official release of the major version you
            purchased (all Zerro {LICENSED_RELEASES} releases); a future{" "}
            {NEXT_MAJOR} major release may require a separate purchase.
          </li>
          <li>
            <Strong>What the purchase is for.</Strong> The {LICENSE_PRICE}{" "}
            pays for SmartScale&rsquo;s official signed and notarized
            distribution of Zerro, the official {LICENSED_RELEASES} update
            service delivered through it, and support. It does not purchase,
            and does not limit, any right you already have under{" "}
            {SOURCE_LICENSE}.
          </li>
          <li>
            <Strong>Provider usage.</Strong> You bring your own OpenAI, Google
            (Gemini), and Anthropic API keys and pay those providers directly
            for usage. Your relationship with each provider, including its
            pricing, processing, and terms, is between you and that provider.
            There is no subscription, credit balance, or hosted generation
            offered by us.
          </li>
        </UL>
        <P>
          Prices may change for future purchases; a license you have already
          bought is not affected. Refunds are handled in accordance with Lemon
          Squeezy&rsquo;s policies and applicable law; contact{" "}
          <a
            href="mailto:support@getzerro.app"
            className="text-foreground underline underline-offset-4"
          >
            support@getzerro.app
          </a>{" "}
          and we&rsquo;ll do our best to make it right.
        </P>
      </LegalSection>

      <LegalSection title="Open source">
        <P>
          Zerro is free software published under the GNU General Public
          License, version 3 or later ({SOURCE_LICENSE}). That license covers
          the source code and the covered executable code in the official
          builds we distribute. It grants you the rights to run, study, copy,
          modify, and redistribute that software, including the right to make
          your own modified build and to remove or change the trial and
          license checks in it. These Terms do not restrict any of those
          rights, and where these Terms and {SOURCE_LICENSE} appear to
          conflict for GPL-covered software, {SOURCE_LICENSE} controls. A
          build you compile yourself (a community build) does not require a
          Zerro license and is not subject to the trial and license mechanics
          described above.
        </P>
        <P>
          The Zerro name, logo, and branding are trademarks of SmartScale.
          Permission to use them is separate from the copyright license for
          the software and is set out in the Zerro trademark policy
          (TRADEMARKS.md in the source repository). Builds you distribute must
          not be represented as official Zerro releases, and reserved Zerro
          branding may not be used contrary to that policy.
        </P>
      </LegalSection>

      <LegalSection title="Acceptable use of the Service">
        <P>
          These rules apply to the Service (the website, checkout, license
          activation, official distribution and update infrastructure,
          support, and the Zerro trademarks). They do not govern how you run,
          study, copy, modify, or redistribute the application, which is
          governed by {SOURCE_LICENSE}. In using the Service, you agree not to:
        </P>
        <UL>
          <li>Use the website, checkout, or support to violate any law or the rights of others, or to defraud us or Lemon Squeezy.</li>
          <li>Share, resell, or publish a license key, or activate a license key you are not entitled to use.</li>
          <li>Represent a modified or third-party build as an official Zerro release, or use reserved Zerro branding contrary to the trademark policy.</li>
          <li>Interfere with or disrupt the integrity or performance of the getzerro.app website or our distribution and update infrastructure.</li>
        </UL>
      </LegalSection>

      <LegalSection title="Your recordings">
        <P>
          You retain all rights to your recordings and to the output generated
          from them. We never receive your recordings, screen frames, audio,
          transcripts, prompts, or results: your Mac prepares the recording
          and sends the prepared frames and transcript directly to the AI
          provider you chose, and transcription either stays on your Mac or
          goes directly to OpenAI on your own key. Because we are not in that
          path, what you record is between you, the people and material on
          your screen, and the provider you send it to.
        </P>
        <P>
          As a matter of applicable law rather than of these Terms, you are the
          one responsible for having the right to record the content on your
          screen and any audio you capture, for any confidentiality,
          non-disclosure, or employment obligations that apply to you, and for
          any data subject to special legal protection (such as protected
          health information under HIPAA or payment card data subject to
          PCI-DSS) that you choose to capture or send to a provider. Zerro is
          not designed or offered for regulated data of that kind. To the
          maximum extent permitted by law, we are not liable for content you
          choose to record or send, or for any consequences of recording
          content you were not authorized to capture.
        </P>
      </LegalSection>

      <LegalSection title="Indemnification">
        <P>
          You agree to indemnify, defend, and hold harmless SmartScale
          Solutions LLC and its members from any third-party claims, damages,
          losses, and reasonable legal fees arising out of: (a) your breach of
          these Terms in using the Service, including sharing, reselling, or
          publishing a license key; (b) your representation of a build as an
          official Zerro release, or your use of Zerro branding contrary to
          the trademark policy; and (c) your use of the website, checkout, or
          support in violation of applicable law. This section does not apply
          to your running, studying, copying, modifying, or redistributing the
          application, or to what you choose to record with it.
        </P>
      </LegalSection>

      <LegalSection title="Third-party services">
        <P>
          The Service relies on Lemon Squeezy (payments and license
          activation), PostHog (optional analytics), and our hosting
          providers. We are not responsible for those third-party services.
        </P>
        <P>
          The application, as you run it, talks to the AI model providers you
          choose (OpenAI, Google (Gemini), Anthropic) using your own API keys,
          and in Dev Mode launches the local coding-agent CLI you select
          (Claude Code, Codex, or Cursor). Those are your own relationships
          under each provider&rsquo;s terms; they are not part of the Service,
          and we are not responsible for them. You may use one or more OpenAI,
          Google (Gemini), and Anthropic API keys. On-device transcription
          does not require a provider key; optional OpenAI transcription
          requires an OpenAI API key and sends audio directly to OpenAI.
        </P>
      </LegalSection>

      <LegalSection title="Intellectual property">
        <P>
          The Zerro software, including the official builds, is licensed to
          you under {SOURCE_LICENSE}, as described in the Open source section;
          that license, not these Terms, governs your rights to copy, modify,
          and redistribute it. The getzerro.app website and its content, and
          the Zerro name, logo, and branding, are owned by SmartScale and
          protected by intellectual property and trademark laws; branding use
          is governed by the trademark policy. Feedback you provide may be
          used by us without obligation.
        </P>
      </LegalSection>

      <LegalSection title="Disclaimers">
        <P>
          THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS
          AVAILABLE&rdquo; WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED,
          INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
          NON-INFRINGEMENT. AI-GENERATED OUTPUT MAY CONTAIN ERRORS; YOU ARE
          RESPONSIBLE FOR REVIEWING IT BEFORE USE. FOR GPL-COVERED SOFTWARE,
          THE WARRANTY DISCLAIMER IN {SOURCE_LICENSE} ALSO APPLIES.
        </P>
        <P>
          The following is a factual disclosure about the application, not a
          condition on your GPL rights. Dev Mode runs a third-party coding
          agent that you select (Claude Code, Codex, or Cursor) locally on
          your computer and at your direction. The agent can read and modify files in the project folder
          you select and run commands on your machine. Zerro applies
          sandboxing and permission controls where the selected agent
          supports them, and they differ by agent; none of them is a
          guarantee that the agent stays inside the folder you select. The
          agent executes commands on your computer and may in some cases
          read, change, or delete files or settings outside that folder, and
          some changes may be permanent and impossible to undo. You are solely
          responsible for reviewing any changes it proposes or makes before
          relying on them, for keeping your own backups, and for using version
          control so changes can be inspected and, where possible, reverted.
          Dev Mode and the agents are provided &ldquo;as is,&rdquo; and to the
          maximum extent permitted by law we are not liable for any changes an
          agent makes to your files, system, or other data (whether inside or
          outside the folder you select, and whether or not those changes can
          be reversed), or for any resulting loss or damage.
        </P>
        <P>
          Zerro&rsquo;s output, including plain-language explanations and
          answers, is provided for general informational purposes only, is
          generated by third-party AI models, and does not constitute
          professional advice of any kind (including legal, medical, financial,
          or tax advice). You should not rely on output as a substitute for a
          qualified professional.
        </P>
      </LegalSection>

      <LegalSection title="Limitation of liability">
        <P>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, SMARTSCALE WILL NOT BE
          LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR
          PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, DATA, OR GOODWILL. OUR
          TOTAL LIABILITY FOR ANY CLAIM ARISING OUT OF THE SERVICE WILL NOT
          EXCEED THE AMOUNT YOU PAID US IN THE TWELVE MONTHS BEFORE THE CLAIM
          AROSE. SOME JURISDICTIONS DO NOT ALLOW THESE LIMITATIONS, SO THEY
          MAY NOT APPLY TO YOU.
        </P>
      </LegalSection>

      <LegalSection title="Termination">
        <P>
          You may stop using the Service at any time. We may revoke a Zerro
          license key, or stop providing official updates and support to you,
          if you materially breach these Terms, including sharing or reselling
          a license key or misrepresenting a build as official. Revoking a
          license key or ending these Terms affects only the official
          distribution, update service, and support that the purchase pays
          for; it does not terminate, and cannot be read as terminating, your
          rights under {SOURCE_LICENSE} to any copy of the software you have
          received. Sections that by their nature should survive termination
          (such as trademark, disclaimers, and limitation of liability)
          survive.
        </P>
      </LegalSection>

      <LegalSection title="Governing law">
        <P>
          These Terms are governed by the laws of the State of Wyoming,
          without regard to conflict of law principles. Disputes will be
          resolved in the state or federal courts located in Wyoming, and you
          consent to their jurisdiction.
        </P>
      </LegalSection>

      <LegalSection title="Dispute resolution">
        <P>
          Except where prohibited by law, any dispute arising out of or
          relating to these Terms or the Service will be resolved through
          binding individual arbitration rather than in court. You and
          SmartScale each waive the right to a jury trial and the right to
          participate in any class or representative action. You may opt out of
          this arbitration agreement by emailing{" "}
          <a
            href="mailto:support@getzerro.app"
            className="text-foreground underline underline-offset-4"
          >
            support@getzerro.app
          </a>{" "}
          within 30 days of first accepting these Terms.
        </P>
      </LegalSection>

      <LegalSection title="Changes to these Terms">
        <P>
          We may update these Terms from time to time. We will post the
          updated version on this page and revise the &ldquo;Last
          updated&rdquo; date; material changes will be notified more
          prominently. Continued use of the Service after changes take effect
          constitutes acceptance; merely continuing to receive or run the
          GPL-covered application does not.
        </P>
      </LegalSection>

      <LegalSection title="Contact">
        <P>
          SmartScale Solutions LLC ·{" "}
          <a
            href="mailto:support@getzerro.app"
            className="text-foreground underline underline-offset-4"
          >
            support@getzerro.app
          </a>
        </P>
      </LegalSection>
    </LegalShell>
  )
}
